config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :prettylinks

  resources :blogs

  root 'pins#index'
  post 'like_pin' => 'socials#like', :as => 'pin_like'
  resources :pins
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get 'home/about'
  get 'home/play_tic_toe'  
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html ,:js

  def index
    @message = Message.new
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    respond_with(@message)
  end

  def new
    @message = Message.new
    respond_with(@message)
  end

  def edit
  end

  def create

    @message = Message.new(message_params)
    @message.save
    PrivatePub.publish_to("/messages/new", message: @message)
    respond_with(@message)
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:user_id, :body)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="col-sm-10">
  <div class="row">
    <div class="col-xs-2 image" style="<%='float:right' if message.id.even?%>">
      <a href="javascript:void(0);">
      <% type =  ""#message.id.even? ? 'pull-right' : 'pull-left'
      	 # side =  message.id.odd? ? 'col-xs-pull-2' : ''
       %>
      	<img title="hello" src="http://api.randomuser.me/portraits/women/22.jpg" style="width:70px;"
      	class="img-thumbnail img-responsive img-circle <%= type %>" ></a>
    </div>  
    <div class="col-xs-10 <%=  %>">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= message.body %>
          <br>
          <span class="label label-info"><%= message.created_at.try(:strftime,"%b %d, %Y") %></span>
        </div>
      </div>
    </div><!--/col-->
  </div><!--/row-->
</div>

app/views/messages/create.js.erb
<% publish_to "/messages/new" do %>
  $("#chat").append("<%= j render(@message) %>");
<% end %>
$("#new_message")[0].reset();
$("#chat")[0].scrollTop =  $("#chat")[0].scrollHeight;

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<script>
//$("#chat")[0].scrollTop =  $("#chat")[0].scrollHeight;

      function ChatController($scope) {
        var socket = io.connect();

        $scope.messages = [];
        $scope.roster = [];
        $scope.name = 'jhvgvghvg';
        $scope.text = '';

        // socket.on('connect', function () {
        //   $scope.setName();
        // });

        // socket.on('message', function (msg) {
        //   $scope.messages.push(msg);
        //   $scope.$apply();
        // });

        // socket.on('roster', function (names) {
        //   $scope.roster = names;
        //   $scope.$apply();
        // });

        $scope.send = function send() {
          console.log('Sending message:', $scope.text);
         // socket.emit('message', $scope.text);
          $scope.text = '';
        };

        // $scope.setName = function setName() {
        //   socket.emit('identify', $scope.name);
        // };
      }
    </script>







<div class="page-header">
<h1>Just chat mitro</h1>
</div>
<div class="row" ng-controller="ChatController">
<div class="span3">
  <ul class="nav nav-list well">
    {{ name }}
  </ul>
</div>
<div class="span9">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="span2">Name</th>
        <th class="span7">Text</th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="msg in messages">
        <td class="span2" ng-bind="msg.name"></td>
        <td class="span7" ng-bind="msg.text"></td>
      </tr>
    </tbody>
  </table>
  <div class="row controls">
    <form ng-submit="send()">
      <div class="span2"><input type="text" class="input-block-level" ng-model="name" ng-change="setName()" placeholder="Your Name"></div>
      <div class="input-append span7">
        <input type="text" class="span6" ng-model="text" placeholder="Message">
        <input type="submit" class="span1 btn btn-primary" value="Send" ng-disabled="!text">
      </div>
    </form>
  </div>
</div>
</div>


















<% if false %>

<h2>Friend's Club Chat Room</h2>
<hr>
<div class="row" id="chat" style=" overflow-y: auto;max-height:330px; margin: 0px 0px 30px 45px;">
    <%= render @messages %>
</div>
<%= simple_form_for(@message , remote: true,style: 'margin-top: 30px;')  do |f| %>
    <%= f.error_notification %>
	<div class="input-group">	
		<input name="message[body]" type="text" id="inputText" placeholder="Add to the conversation" class="form-control input-large" required >
		<span id="send" class="input-group-addon" style="cursor: pointer;" onClick="if($('#inputText').val()) $('#new_message').submit();">Post</span>
	</div>
<% end %>
<%= subscribe_to "/messages/new" %>

<style>
div.image:nth-child(even) {
   float:right;
}
</style>
<% end %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>