config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :prettylinks

  resources :blogs

  root 'pins#index'
  post 'like_pin' => 'socials#like', :as => 'pin_like'
  resources :pins
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get 'home/about'
  get 'home/play_tic_toe'  
end

app/models/pin.rb
class Pin < ActiveRecord::Base
    
    acts_as_likeable
    belongs_to :user
    has_attached_file :image, :styles => { :medium => "240x300>", :thumb => "50x50>", :normal => "420x680>"  },
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
                    
    validates_presence_of :descrption,:image              
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user! , only: [:edit, :update, :destroy ,:create,:new]

  respond_to :html

  def index
    
    @pins = Pin.all.order("created_at DESC")
                   .paginate(:page => params[:page], :per_page => 9)
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
       redirect_to @pin , notice: "Pin was successfully created"
    else
      render action: 'new'
    end  
  end

  def update
    @pin.update(pin_params)
    if  @pin.update(pin_params)
        redirect_to @pin , notice: "Pin was successfully created"
    else
      render action: 'edit'
    end  
  end

  def destroy
    @pin.destroy
     redirect_to pins_path
  end
  
  def like_pin
      current_user.like!(pin)
  end 

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:descrption,:image)
    end
    
     
end

  def correct_user
    @pin =current_user.pins.find(params[:id])
  end  

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for @pin , :validate => true ,html: { multipart: true } do |f| %>
      <% if @pin.errors.any? %>
        <div id="error_explanation">
          <h2>
              <%= pluralize(@pin.errors.count, "error") %>
              prohibited this pin from being saved:
          </h2>
          <ul>
            <% @pin.errors.full_messages.each do |message| %>
              <li>
                  <%= message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :descrption %><br>
        <%= f.text_field :descrption, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :image %><br>
        <%= f.file_field :image, class:"form-control" ,style:"display:none",id:"lefile" %>
        
          <div class="input-append",style:"color:red">
          <a class="btn" onclick="$('input[id=lefile]').click();">Browse</a>
          </div>
 

      </div>
      <div class="actions">
        <%= f.submit "Create Pin", :class=>"btn btn-primary" %>
      </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
        <h1>Editing pin</h1>
   </div>
   <div class="panel-body">
        <%= render 'form' %>
    </div>
    <div class="panel-body">
       <%= link_to 'Show', @pin %> |
       <%= link_to 'Back', pins_path %>
    </div>
</div>    
    

app/views/pins/index.html.erb
<%= render "home/jumbo" unless user_signed_in? %>
 <div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
        <div class="box">
            <div class="panel panel-default">
                <%= link_to image_tag(pin.image.url(:medium)) ,pin%>
                <div class="panel-body">
                    <%= pin.descrption %><br />
                    <strong><%= pin.user.first_name %></strong>    
                </div>
                <% if pin.user == current_user %>
                    <div class="panel-footer">
                        <%= link_to 'Edit', edit_pin_path(pin) %>
                        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                <% end %>
            </div>        
        </div>   
    <% end %>
 </div>
  <div class="center">
     <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
  </div>

app/views/pins/new.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
     <h1>New pin</h1>
   </div>
   <div class="panel-body">
        <%= render 'form' %>
    </div>
    <div class="panel-body">
        <%= link_to 'Back', pins_path %>
    </div>
</div>    
    

app/views/pins/show.html.erb
<div class="row">
     <div class="col-md-offset-2 col-md-8 center">
          <div class="panel panel-default center">
                  <div class="panel-heading ">
                  <%= image_tag  @pin.image.url(:normal)%>
                  </div>
                <div class="panel-body">
                    <%= @pin.descrption %><br />
                     <%= like_for(@pin) %>
                     <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                  <strong><%= @pin.user.fullname %></strong> <br />   
                <% if user_signed_in? %>  
                    <% if @pin.user == current_user %>
                       <%= link_to 'Edit', edit_pin_path(@pin) %>
                    <% end %> 
                <% end %>     
                    <%= link_to 'Back',pin_path %>
                    
                </div>    
            </div>  
        </div>
    </div>
</div>    