config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :prettylinks

  resources :blogs

  root 'pins#index'
  post 'like_pin' => 'socials#like', :as => 'pin_like'
  resources :pins
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get 'home/about'
  get 'home/play_tic_toe'  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'play_tic_toe', :only => [:play_tic_toe]
  def index88
  end
  
  def play_tic_toe
  end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Photo Share",root_path,:class=>"navbar-brand" %>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",root_path %></li>
        <li><%= link_to "About Me",home_about_path %></li>
          
        <% if user_signed_in? %>
          <li><%= link_to current_user.fullname ,"#"  %></li>
          <li><%= link_to "Logout" ,destroy_user_session_path,method: :delete  %></li>
          <li><%= link_to "Edit Profile" , edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Login" , new_user_session_path %></li>
          <li><%= link_to "Join" , new_user_registration_path  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_jumbo.html.erb
<div class="jumbotron center">
        <h1>Welcome to My Photo Share App !</h1>
        <p>Preety Cool , Don't you think</p>
         
         <% if user_signed_in? %>
             <%= link_to "Logout" ,destroy_user_session_path,method: :delete, :class=>"btn btn-primary"  %>
             <%= link_to "Edit Profile" , edit_user_registration_path, :class=>"btn btn-default" %>
        <% else %>
             <%= link_to "Login" , new_user_session_path , :class=>"btn btn-default" %>
             <%= link_to "Join" , new_user_registration_path , :class=>"btn btn-primary" %>
        <% end %>
        
</div>

app/views/home/about.html.erb
<div>
	<div class="col-sm-3">	
	<div style="margin-top:30px;">
		<img class='img-thumbnail img-rounded'src="https://dl.dropboxusercontent.com/1/view/7sbejfrc8w65r2n/Apps/my_photo_share/20150715_142228_normal.jpg" style="width:200px;">
	</div>
		
	</div>
	<div class="col-sm-9">
		<h1>Hi , My name is Sourav Kumar</h1>
<hr/>
<h3>About Me</h3>
<p>
	I am a passionate Rubyist and an active member of the Ruby on Rails source community. When I am not coding or writing i am enjoys Playing cricket ,fun with friends (sometimes at the same time). I also like to visit new place and making new friends.
</p>
<p>
	I've experience of 1 years and 4 months. I have good experience with HTML5/CSS3, HAML, SASS, Javascript, jQuery, AJAX, Mysql, Ruby 1.9.x and 2.x, Rails (3.x, 4), rspec, Git, svn, JIRA,Trello, Facebook API, Bootstrap, coffeescript, Social Media integration, AWS S3, AngularJS.
</p>


<h3> Contact info :</h3>
<div>
	<span>
		E-mail:
	</span> 
	<span>
		<%= mail_to "souravbhadani94@gmail.com"%>
			
	</span>
</div>
<div>
	<span>
		Twitter:
	</span> 
	<span>
		<%= link_to '@sourav_bhadani',"https://twitter.com/sourav_bhadani",title:"Twitter Handel"%> 
	</span>
</div>
<div>
	<span>
		Github:
	</span> 
	<span>
		<%= link_to 'github.com/souravbhadani',"https://github.com/souravbhadani",title:"Github Profile"%> 	
	</span>
</div>
<div>
	<span>
		LinkedIn:
	</span> 
	<span>
		<%= link_to 'in.linkedin.com/in/souravbhadani',"https://in.linkedin.com/in/souravbhadani",title:"LinkedIn Profile"%> 	
		
	</span>
</div>
<div>
	<span>
		Mobile:
	</span> 
	<span>
		+918750902613
	</span>
</div>

	</div>
</div>

app/views/home/index88.html.erb
<h1>Home#index88</h1>
<p>Find me in app/views/home/index88.html.erb</p>

app/views/home/play_tic_toe.html.erb
    <div class="wrapper">
      <header class="text-center">
        <h1>Tic Tac Toe</h1>
        <p class="lead">Defeat your friends and show no mercy</p>
      </header>

      <div id="board"></div>
      <div class="alerts welcome"></div>
      <div class="notifications"></div>

      <form action="" method="POST">
        <div class="input-group">
          <div class="input-group-addon">Player 1</div>
          <input name="pl-1" class="form-control" type="text" value=""/>
        </div>
        <div class="input-group">
          <div class="input-group-addon">Player 2</div>
          <input name="pl-2" class="form-control" type="text" value=""/>
        </div>
        <div class="text-center">
          <input type="submit" class="btn btn-lg btn-primary" value="Start"/>
        </div>
      </form>
    </div>