config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :prettylinks

  resources :blogs

  root 'pins#index'
  post 'like_pin' => 'socials#like', :as => 'pin_like'
  resources :pins
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get 'home/about'
  get 'home/play_tic_toe'  
end

app/models/prettylink.rb
class Prettylink < ActiveRecord::Base
    belongs_to :user
    extend FriendlyId
    friendly_id :title, use: :slugged
    def self.find(user)
     friendly.find(user)
    end 
end

app/controllers/prettylinks_controller.rb
class PrettylinksController < ApplicationController
  before_action :set_prettylink, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:edit, :update, :destroy ,:create,:new]

  respond_to :html

  def index
    @prettylinks = Prettylink.all
    respond_with(@prettylinks)
  end

  def show
    respond_with(@prettylink)
  end

  def new
    @prettylink = current_user.prettylinks.build
    respond_with(@prettylink)
  end

  def edit
  end

  def create
    @prettylink = current_user.prettylinks.build(prettylink_params)
    @prettylink.save
    respond_with(@prettylink)
  end

  def update
    @prettylink.update(prettylink_params)
    respond_with(@prettylink)
  end

  def destroy
    @prettylink.destroy
    respond_with(@prettylink)
  end

  private
    def set_prettylink
      @prettylink = Prettylink.find(params[:id])
    end

    def prettylink_params
      params.require(:prettylink).permit(:url, :title, :image, :user_id)
    end
end

app/helpers/prettylinks_helper.rb
module PrettylinksHelper
end

app/views/prettylinks/_form.html.erb
<%= simple_form_for(@prettylink) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :url %>
    <%= f.input :title %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/prettylinks/edit.html.erb
<h1>Editing prettylink</h1>

<%= render 'form' %>

<%= link_to 'Show', @prettylink %> |
<%= link_to 'Back', prettylinks_path %>

app/views/prettylinks/index.html.erb
<h1>Listing prettylinks</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
     
    </tr>
  </thead>

  <tbody>
    <% @prettylinks.each do |prettylink| %>
      <tr>
        <td><%= link_to  prettylink.title,prettylink.url,target: '_blank',title: prettylink.title %></td>
       </tr>
    <% end %>
    
  </tbody>
</table>

app/views/prettylinks/new.html.erb
<h1>New prettylink</h1>

<%= render 'form' %>

<%= link_to 'Back', prettylinks_path %>

app/views/prettylinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @prettylink.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @prettylink.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @prettylink.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @prettylink.user_id %>
</p>

<%= link_to 'Edit', edit_prettylink_path(@prettylink) %> |
<%= link_to 'Back', prettylinks_path %>